### ISSUE TITLE
[1.14.4] Crash

### ISSUE THREAD

**Issue by revdave33** [EwyBoy/World-Stripper#10]
###### **Minecraft Version**
1.14.4

###### **Forge Version & World-Stripper**
forge-28.0.102
World-Stripper-1.7.0-1.14.4

Crash on Starting Forge
[latest.log](https://github.com/EwyBoy/World-Stripper/files/3596276/latest.log)

**Comment by EwyBoy** [comment]
Is this the complete log file? This does not really tell me anything.

**Comment by EwyBoy** [comment]
Thanks for the crash report. I was able to tarck down the bug. There was a typo in the metadata file causing forge to not wanna start. 
Patch can be found here: https://www.curseforge.com/minecraft/mc-mods/world-stripper/files/2782444
