### ISSUE TITLE
Game lagged then crashed soon after, "NoSuchMethodError: func_151468_f()Z"

### ISSUE THREAD

**Issue by dudeawsomeness1** [EwyBoy/World-Stripper#12]
###### **Minecraft Version**
> 1.14.4

###### **Forge Version & World-Stripper**
> forge-1.14.4-28.2.0_mapped_snapshot_20190719-1.14.3-recomp  &  1.7.2-1.14.4

###### **Expected behavior**
> No crashing and no lag

###### **Actual Behavior**
> Soon after loading into a world the game lagged then crashed

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> https://pastebin.com/6greRyfH

###### **Steps to reproduce** *[If Applicable]*
> Seems to happen when exiting furnace GUI maybe

**Comment by EwyBoy** [comment]
Something might have changed in Forge that causes my key input handler to crash the client.
Imma look into it.

**Comment by EwyBoy** [comment]
Are you on a server?

**Comment by dudeawsomeness1** [comment]
> Are you on a server?

Uhm not sure actually I ran into this while testing a simple mod I'm developing with gradle runClient, so maybe that's affecting it? I don't think my mod would affect it, would it?

**Comment by EwyBoy** [comment]
Hmm, I am actually not sure. I was not able to reproduce the bug. I am using this mod in my dev enviroments all the time and never had anything like this happen either.

**Comment by Davoleo** [comment]
I am experiencing the same crash in a dev env on 1.15.2

**Comment by Davoleo** [comment]
Maybe it's a client-only method that is being called on both sides?
just putting down some thoughts (since it's related to keybindings)

**Comment by dudeawsomeness1** [comment]
I think there is something weird with how the developer environment works, I think it will crash the game in a similar manner with other mods too, so perhaps it is not the mod, maybe it is a specific forge thing.
