### ISSUE TITLE
Question: How can I add this in my project

### ISSUE THREAD

**Issue by congueror** [EwyBoy/World-Stripper#13]
Am a mod-maker and I would like to know how I can add this mod to my environment so I can test out world-gen. Do I need a flatdir or do I also need repositories and stuff?

**Comment by EwyBoy** [comment]
I am working on setting up a maven so the mod can be added simply by adding a line of code to the build.gradle file.
I will get back to you.

**Comment by EwyBoy** [comment]
Sorry this took so long. You can add a maven dependency in your build.gradle file by using https://github.com/EwyBoy/World-Stripper/packages/394476 from version 1.16 of Minecraft and above.
