### ISSUE TITLE
2.0.0 dedicated server crash

### ISSUE THREAD

**Issue by Terpo** [EwyBoy/World-Stripper#15]
###### **Minecraft Version**
1.16.4

###### **Forge Version & World-Stripper**
2.0.0 with 1.16.4 forge recommended

###### **Expected behavior**
works

###### **Actual Behavior**
does not work ¯\_(ツ)_/¯
Crash on dedicated server start
server uses client api

###### **Link to Crashlog or Forgelog** *[If Applicable]*
https://gist.github.com/Terpo/63d3b333bd62edd0ca4bcf6f3feb270d

###### **Steps to reproduce** *[If Applicable]*
start dedicated server

**Comment by EwyBoy** [comment]
Hey, I will try to get this fixed ASAP.  
The mod is not intended to run on servers but it is not supposed to crash either.

Thanks for the report.

**Comment by NillerMedDild** [comment]
If the client has the mod and the server does not, the client cannot connect either.

**Comment by EwyBoy** [comment]
> If the client has the mod and the server does not, the client cannot connect either.

The mod has to be installed on both the server and client for it to work. It is not a client side mod.

**Comment by NillerMedDild** [comment]
Ah Right, I misunderstood "The mod is not intended to run on servers" :)

**Comment by EwyBoy** [comment]
> Ah Right, I misunderstood "The mod is not intended to run on servers" :)

Yes, sorry. To clarify; The mod is a debugging tool for pack /  makers in the first place. It's originally not intended to be used as a survival mod like most normal mods. Although I can definitely see use cases for server admins and such to use this as a world editing tool.
I am working on a fix now 👯

**Comment by Terpo** [comment]
To be fair, I had that issue as a mod pack dev while debugging. I will not put that mod on to my actual server later on as its a bit risky. But its quite easy possible to share the mods folder between client and server. Just simply extract the server stuff into the client folder, thats all. With that the development of a pack feels more like a real world scenario for me.

**Comment by EwyBoy** [comment]
Fixed the server crash on launch.
https://www.curseforge.com/minecraft/mc-mods/world-stripper/files/3142092

Although the mod does not currently do anything when ran on a server due to some networking / packet issues.
Will get fixed when I get time over Christmas. But at least it does not crash the servers anymore.
