### ISSUE TITLE
[1.16.5] Cannot alter profiles while in game

### ISSUE THREAD

**Issue by ZigTheHedge** [EwyBoy/World-Stripper#19]
I cannot add or remove blocks from profiles, although I can see messages about "... was added to strip Profile X" in chat. 
And even more: I cannot add blocks using in-game config GUI (nothing is happening when I press "X" button to delete block from profile or pushing "Add" button. I think there's something with the new forge maybe? Because all config files are resetting to their initial states when I'm trying to edit it if the game is running. I can edit them easily while in minecraft Main Menu.
Minecraft: 1.16.5
Forge: 36.1.32
World Stripper: 2.0.2

**Comment by EwyBoy** [comment]
I will look into it, it has been a bit buggy lately.

**Comment by EwyBoy** [comment]
World Stripper 2 was a buggy mess. Most of this issues have been fixed in World Stripper 3
