### ISSUE TITLE
Publish 1.11 source

### ISSUE THREAD

**Issue by shadowfacts** [EwyBoy/World-Stripper#2]
I'd like to be able to build a custom version of World-Stripper for use on 1.11 that strips Netherrack for until #1 is merged. I can't do this at the moment, because the source code for the 1.11 version isn't on GitHub.

**Comment by EwyBoy** [comment]
I think the 1.10 source is exactly the same as the 1.11 source. Thats why I forgot to upload it.
I am on vacation right now. Gonna make a whitelist in the config when I get home.

**Comment by EwyBoy** [comment]
Added a white-list to config for blocks to do strip away so you can customize yourself what blocks to strip.
 https://minecraft.curseforge.com/projects/world-stripper

**Comment by shadowfacts** [comment]
Awesome, thanks!
