### ISSUE TITLE
[Feature] Strip Below Y= -64

### ISSUE THREAD

**Issue by Darkosto** [EwyBoy/World-Stripper#22]
**Is your feature request related to a problem?**
Hello! I am crazy and set my world to have -512 blocks below 0. World Stripper only goes -64, could you allow a setting to go lower?

**Describe the solution you'd like**
I would like to customize stripping to my desires.

**Describe alternatives you've considered**
No

**Additional context**
pls halp

**Comment by EwyBoy** [comment]
Hahha, sorry did not know you could go below -64. Creating a fix to strip until we hit bedrock, sounds good?
