### ISSUE TITLE
[Bug] 3.1.0 not compatible with 1.18.1

### ISSUE THREAD

**Issue by recon88** [EwyBoy/World-Stripper#23]
3.1.0 seems to have broken compatibility with lower versions than 1.18.2.
See https://github.com/FabricMC/fabric/issues/2040 for explanation and crash log.
You should remove the 1.18 and 1.18.1 tags on curse so modpack launchers don't pull that version for 1.18/.1 packs.

**Comment by EwyBoy** [comment]
Thank you, did not catch that one. 
Files have been updated like you said.
Thanks for reporting 😃
