### ISSUE TITLE
Empty Config

### ISSUE THREAD

**Issue by Niltak** [EwyBoy/World-Stripper#3]
Version: 1.2.0

Loaded the game which generated an Empty Config for this mod.

I have deleted and reloaded the game to regen the Config, but it did nothing.

Thanks for the mod!

Has really helped me figure out ore gen.

-Niltak

**Comment by EwyBoy** [comment]
What MC version

**Comment by Niltak** [comment]
Sorry Minecraft Version: 1.10.2

**Comment by EwyBoy** [comment]
The issue have been resolved : Grab the 1.2.1-build for fix here : https://minecraft.curseforge.com/projects/world-stripper/files/2376331
Thank you for your time and bug report!

**Comment by Niltak** [comment]
Thanks man! Have a great day!

**Comment by EwyBoy** [comment]
You too!
