### ISSUE TITLE
[Bug] World stripper only works up to y=256

### ISSUE THREAD

**Issue by XnoobSpeakable** [EwyBoy/World-Stripper#30]
###### **Minecraft Version**
> 1.20.1

###### **Forge Version**
> 47.3.0

###### **Mod Version**
> 3.3.0

###### **Describe the bug**
> It only strips the world up to y=256, higher terrain is not stripped.

###### **How to reproduce**
> Use any customised world (such a datapack world) that has terrain above y=256

(crash not applicable, it doesnt crash)

###### **Screenshots / Images**
> ![image](https://github.com/EwyBoy/World-Stripper/assets/62246474/2273ba08-6151-41e6-b5a8-f9bd2a11173c)

![image](https://github.com/EwyBoy/World-Stripper/assets/62246474/b4f29350-497e-4d57-b98c-4cbeab784856)

**Comment by EwyBoy** [comment]
You can edit the mods config files values startY and stopY to change where the strip starts and stops.
