### ISSUE TITLE
Meta Data Blocks Do Not Strip

### ISSUE THREAD

**Issue by Darkosto** [EwyBoy/World-Stripper#5]
Could you please consider adding the ability to remove blocks with meta data? Many of the worldgen blocks like chisel use meta. Or do I need to use 2 dollar bills instead?

Thanks!
Darkosto

**Comment by EwyBoy** [comment]
Sure, I look into it first thing in the morning^^

**Comment by EwyBoy** [comment]
It is now fixed, I was not able to get the click to add block feature but I you can now press HOME or any other key you deice to bind it to inspect the block you are looking at and it will print the full registry name for you like:
minecraft:dirt

you can also shift inspect to read out the registry name with meta to, like:
minecraft:dirt[snow=false]

also I added a setting to change the update flag. So if you change it from 3(default) to 2 it will strip the blocks away but not cause any block updates, so stuff like fluids will not start flowing until you force update em by placing a block next to it.

https://minecraft.curseforge.com/projects/world-stripper/files
