### ISSUE TITLE
Customized profile lists are ignored

### ISSUE THREAD

**Issue by tyra314** [EwyBoy/World-Stripper#6]
`BlocksToStrip.blockList` doesn't seem right: https://github.com/EwyBoy/World-Stripper/blob/master/src/main/java/com/ewyboy/worldstripper/common/network/PacketStripWorld.java#L51

Should be something around this: `Config.stripProfile[Config.profile]`

**Comment by EwyBoy** [comment]
This is the old src code. I haven't updated it.

**Comment by tyra314** [comment]
Okay, then I have to rephrase the issue...

###### **Forge Version & World-Stripper**
MC: 1.12.2
Forge: 14.23.1.2561
WS: 1.5.0-1.12.2

###### **Expected behavior**
Blocks added to the profile lists should be stripped

###### **Actual Behavior**
They don't.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
---

###### **Steps to reproduce** *[If Applicable]*
Add an additional block to the used profile, which isn't part of the default. For example `minecraft:gold_block`. Place this block in the world at your feets. Strip world. Block still there.

**Comment by EwyBoy** [comment]
okey, I can that was a bit easier to understand. I will look into it.

**Comment by EwyBoy** [comment]
Found the issue. It was a tiny typo from copy / pasting: https://github.com/EwyBoy/World-Stripper/blob/cb023cccd8cb4d086c40ea012d656a7eb9727b84/src/main/java/com/ewyboy/worldstripper/common/util/Config.java#L76

Pushing 5 builds for version 1.8 to 1.12 now. Should be named 1.5.1 and be up on CurseForge soon.

Thanks for the report and info!
-Ewy
