### ISSUE TITLE
Player kicked with fatal error - java.lang.AbstractMethodError: null

### ISSUE THREAD

**Issue by ProsperCraft** [EwyBoy/World-Stripper#7]
###### **Forge Version & World-Stripper**
> forge-1.12.2-14.23.1.2598-universal
 World-Stripper-1.5.1-1.12.2.jar

###### **Expected behavior**
> Type here

###### **Actual Behavior**
> Player kicked from server with fatal error, console shows stacktrace.

###### **Link to Crashlog or Forgelog** *[If Applicable]*
> Read the second group- there was a middle group as well, but none of these stack traces were showing in logs so I had to pull them from console. https://gist.github.com/ProsperCraft/a57724d3b47b2671c271422a4085249c

###### **Steps to reproduce** *[If Applicable]*
> Unable, non-opped player was mining at the time.

**Comment by EwyBoy** [comment]
Looks like it is something to do with packets, gonna look into it.

**Comment by EwyBoy** [comment]
Never found anything. Hard to replicate. Is not legacy and wont fix.
