### ISSUE TITLE
Add support for wildcard * in config

### ISSUE THREAD

**Issue by IronPiston** [EwyBoy/World-Stripper#9]
###### **Minecraft Version**
> 1.12.2

###### **Forge Version & World-Stripper**
> 14.23.5.2838 & 1.6.0

###### **Expected behavior**
> Typing modname:blockname:* should strip blockname with any metadata

###### **Actual Behavior**
> Doesn't strip any blockname

###### **Steps to reproduce** *[If Applicable]*
> Add "modname:blockname:*" for any block with metadata, and strip a region

**Comment by EwyBoy** [comment]
Sure, I will get this fixed when I am back from vacation.
